name: Manual - Run in All Browsers

env:
  GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
  GOOGLE_CLIENTID: ${{ secrets.GOOGLE_CLIENTID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

on:
  workflow_dispatch:

jobs:
  firefox: # Firefox not working Related: https://github.com/cypress-io/cypress/issues/23186
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - name: Checkout
        uses: actions/checkout@v3
      - name: firefox
        id: firefox
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          spec: 'cypress/e2e/**'
          headed: true
          build: yarn install --frozen-lockfile
          record: false
      # # Only record to cypress dashboard on failure (to save on limited tests in free plan)
      # - name: firefox failure record
      #   if: failure() && steps.firefox.outcome == 'failure'
      #   uses: cypress-io/github-action@v4
      #   with:
      #     browser: firefox
      #     spec: 'cypress/e2e/trigger/**'
      #     headed: true
      #     build: npm install
      #     record: true

  edge: # TODO: Reducing to use just electron until we can get things stable for a bit.
    # force jobs to run sequentially.
    needs: firefox
    runs-on: windows-latest
    if: always()
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v3

      - name: edge
        id: edge
        uses: cypress-io/github-action@v5
        with:
          browser: edge
          spec: 'cypress/e2e/**'
          headed: true
          build: yarn install --frozen-lockfile
          record: false
      # # Only record to cypress dashboard on failure (to save on limited tests in free plan)
      # - name: edge failure record
      #   if: failure() && steps.edge.outcome == 'failure'
      #   uses: cypress-io/github-action@v4
      #   with:
      #     browser: edge
      #     spec: 'cypress/e2e/trigger/**'
      #     headed: true
      #     build: npm install
      #     record: true

  chrome:
    # force jobs to run sequentially.
    needs: edge
    runs-on: ubuntu-latest
    if: always()
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v3

      - name: edge
        id: edge
        uses: cypress-io/github-action@v5
        with:
          browser: edge
          spec: 'cypress/e2e/**'
          headed: true
          build: yarn install --frozen-lockfile
          record: false
      # # Only record to cypress dashboard on failure (to save on limited tests in free plan)
      # - name: chrome failure record
      #   if: failure() && steps.chrome.outcome == 'failure'
      #   uses: cypress-io/github-action@v4
      #   with:
      #     browser: chrome
      #     spec: 'cypress/e2e/trigger/**'
      #     headed: true
      #     build: npm install
      #     record: true

  electron:
    # force jobs to run sequentially.
    needs: chrome
    runs-on: ubuntu-latest
    if: always()
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v3

      - name: electron
        id: electron
        uses: cypress-io/github-action@v5
        with:
          browser: electron
          spec: 'cypress/e2e/**'
          headed: true
          build: yarn install --frozen-lockfile
          record: false
      # Only record to cypress dashboard on failure (to save on limited tests in free plan)
      # - name: electron failure record
      #   if: failure() && steps.electron.outcome == 'failure'
      #   uses: cypress-io/github-action@v4
      #   with:
      #     browser: electron
      #     spec: 'cypress/e2e/trigger/**'
      #     headed: true
      #     build: npm install
      #     record: true
