name: Trigger Daily - Test One (cypress-split)

env:
  GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
  GOOGLE_CLIENTID: ${{ secrets.GOOGLE_CLIENTID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}

  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Cypress
  CYPRESS_RECORD_KEY: ${{ vars.CYPRESS_RECORD_KEY }}
  PROJECT_ID: ${{ vars.PROJECT_ID }}

  # Links
  DEV_APP_URL: ${{ vars.DEV_APP_URL }}
  PROD_APP_URL: ${{ vars.PROD_APP_URL }}
  DEV_MARKETING_SITE_URL: ${{ vars.DEV_MARKETING_SITE_URL }}
  DEV_API_URL: ${{ vars.DEV_API_URL }}
  APP_EMAIL_SENDER: ${{ vars.APP_EMAIL_SENDER }}

  # Add credit card data
  AUTHORIZE_DEV_API_LOGIN_ID: ${{ secrets.AUTHORIZE_DEV_API_LOGIN_ID }}
  AUTHORIZE_DEV_TRANSACTION_KEY: ${{ secrets.AUTHORIZE_DEV_TRANSACTION_KEY }}

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}

    steps:
      - name: Print .env
        run: echo "DEV_MARKETING_SITE_URL => ${{ vars.DEV_MARKETING_SITE_URL }}"

      # generate the list using a bash script
      - name: Create matrix ⊹
        id: prepare
        # for reusable workflow, must use the full action reference
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 1 # number of containers to output

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

      - name: Print cypress info 🖨
        run: npx cypress info

      - name: Print node version 🖨
        run: node -v

      - name: Print OS and CPUs 🖨
        run: node -p 'os.cpus()'

  chrome:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Print GitHub variables 🖨
        run: npx @bahmutov/print-env GITHUB

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Run split Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: 'cypress/e2e/trigger/prepare-accounts.cy.js'
          build: yarn install --frozen-lockfile
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          DEBUG: cypress-split
  firefox:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Print GitHub variables 🖨
        run: npx @bahmutov/print-env GITHUB

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Run split Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          spec: 'cypress/e2e/trigger/prepare-accounts.cy.js'
          build: yarn install --frozen-lockfile
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          DEBUG: cypress-split
  electron:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Print GitHub variables 🖨
        run: npx @bahmutov/print-env GITHUB

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Run split Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          browser: electron
          spec: 'cypress/e2e/trigger/prepare-accounts.cy.js'
          build: yarn install --frozen-lockfile
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          DEBUG: cypress-split
